import os

from dotenv import load_dotenv
from langchain_community.chat_models import ChatTongyi
from langchain_community.embeddings import DashScopeEmbeddings
from langchain_core.messages import SystemMessage, HumanMessage
from mem0 import Memory, MemoryClient
from mem0.configs.base import MemoryConfig
from mem0.embeddings.configs import EmbedderConfig
from mem0.graphs.configs import GraphStoreConfig
from mem0.llms.configs import LlmConfig
from mem0.vector_stores.configs import VectorStoreConfig

# https://blog.futuresmart.ai/integrating-mem0-with-langchain
# https://docs.mem0.ai/integrations/langchain

custom_prompt = """
Please only extract entities containing patient health information, appointment details, and user information. 
Here are some few shot examples:

Input: Hi.
Output: {{"facts" : []}}

Input: The weather is nice today.
Output: {{"facts" : []}}

Input: I have a headache and would like to schedule an appointment.
Output: {{"facts" : ["Patient reports headache", "Wants to schedule an appointment"]}}

Input: My name is Jane Smith, and I need to reschedule my appointment for next Tuesday.
Output: {{"facts" : ["Patient name: Jane Smith", "Wants to reschedule appointment", "Original appointment: next Tuesday"]}}

Input: I have diabetes and my blood sugar is high.
Output: {{"facts" : ["Patient has diabetes", "Reports high blood sugar"]}}

Return the facts and patient information in a json format as shown above.
"""


llm = ChatTongyi(model="qwen-plus", api_key="sk-f256c03643e9491fb1ebc278dd958c2d"
)

embeder = DashScopeEmbeddings(model="text-embedding-v2", dashscope_api_key = "sk-f256c03643e9491fb1ebc278dd958c2d")

# 1. 配置 Memory
config = MemoryConfig( llm = LlmConfig( provider="langchain", config={"model":llm }, ),
    embedder = EmbedderConfig( provider = "langchain", config= { "model":embeder} ),
    vector_store = VectorStoreConfig(provider = "qdrant",
                                     config={
                                         "host": "localhost",
                                         "port": 6333,
                                         "collection_name": "memory_vectors",
                                         "embedding_model_dims": 1536,
                                     }
                                     ),
    custom_fact_extraction_prompt = custom_prompt

    # graph_store=  GraphStoreConfig(provider = "neo4j",
    #                                    config= {
    #                                     "url": "bolt://localhost:7687",
    #                                     "username": "neo4j",
    #                                     "password": "myhome1234"
    #
    #                                     }
    #             ),

    )

load_dotenv()
MEM0_API_KEY = os.getenv("MEM0_API_KEY")

class AIHealthcareSupport:
    def __init__(self, config):
        """
        Initialize the AI Healthcare Support with Memory Configuration and Langchain OpenAI Chat Model.

        :param config: Configuration for memory and model settings.
        """




        # self.memory = MemoryClient(api_key=MEM0_API_KEY)
        self.memory  = Memory(config=config)
        # self.memory = Memory.from_config(config)
        self.app_id = "app-1"
        self.model = llm

    def ask(self, question, user_id=None):
        """
        Ask a question to the AI and store the relevant facts in memory.

        :param question: The question to ask the AI.
        :param user_id: Optional user ID to associate with the memory.
        :return: Response from the AI along with the original question.
        """
        # Retrieve relevant memories using the search_memory method
        memories = self.search_memory(question, user_id=user_id)

        context = "Relevant information from previous conversations:\n"
        if memories['results']:
            for memory in memories['results']:
                context += f" - {memory['memory']}\n"

        messages = [
            SystemMessage(content=f"""You are a helpful healthcare support assistant. Use the provided context to personalize your responses and remember user health information and past interactions. {context}"""),
            HumanMessage(content=question)
        ]

        response = self.model.invoke(messages)

        # Store the interaction in memory
        self.add_memory(question, response.content, user_id=user_id)
        return {"messages": [response.content]}

    def add_memory(self, question, response, user_id=None):
        """
        Add a memory entry to the memory store.

        :param question: The question that was asked by the user.
        :param response: The response generated by the AI.
        :param user_id: Optional user ID to associate with the memory.
        """
        self.memory.add(f"User: {question}\nAssistant: {response}", user_id=user_id, metadata={"app_id": self.app_id})

    def get_memories(self, user_id=None):
        """
        Retrieve all memories associated with the given user ID.

        :param user_id: Optional user ID to filter memories.
        :return: List of memories.
        """
        return self.memory.get_all(user_id=user_id)

    def search_memory(self, query, user_id=None):
        """
        Search for memories related to the given query and user ID.

        :param query: The query to search for in the memories.
        :param user_id: Optional user ID to filter memories.
        :return: List of relevant memories.
        """
        related_memories = self.memory.search(query, user_id=user_id)
        return related_memories


if __name__ == '__main__':
    # Initialize the AIHealthcareSupport bot
    ai_support = AIHealthcareSupport(config)
    # User ID for interaction
    user_id = "James"

    # Interacting with the bot
    print("Interacting with AI Healthcare Support:\n")

    # Example interactions
    questions = [
        "I have a family history of diabetes; how can I reduce my risk?",  # Preventive care inquiry
        "Can you recommend any specific dietary changes?",  # Focusing on diet
        "I have a headache and would like to schedule an appointment."
    ]

    # Loop through each question, ask the bot, and print responses
    for question in questions:
        response = ai_support.ask(question, user_id=user_id)
        print(f"User: {question}")
        print(f"AI: {response['messages'][0]}\n")

    # Retrieve and display memories associated with the user
    memories = ai_support.get_memories(user_id=user_id)
    print("All Memories:")
    for memory in memories['results']:
        print(f"- {memory}")

